export const NavigationState = Object.freeze({
    welcome_init: Symbol("WELCOME"),
    registration: Symbol("Registration"),
    welcome_registration_completed: Symbol("REG_COMPLETED"),
    login: Symbol("Login"),
    private_login_completed: Symbol("PRIVATE"),
    welcome_login_completed: Symbol("LOGIN_COMPLETED"),
    shortcodeGeneration: Symbol("SHORTCODE_GENERATION"),
    shortcodeAuthorization_shortcodeInput: Symbol("SHORTCODE_INPUT"),
    shortcodeAuthorization_authorizationScreen: Symbol("SHORTCODE_AUTHORIZATION"),
    private_shortcode_completed: Symbol("PRIVATE_SHORTCODE_COMPLETED"),
    welcome_shortcode_completed: Symbol("SHORTCODE_COMPLETED"),
    eid_registration: Symbol("EID_REGISTRATION"),
    private_eid_registration_completed: Symbol("PRIVATE_SHORTCODE_COMPLETED"),
    welcome_eid_registration_completed: Symbol("EID_REGISTRATION_COMPLETED"),
    eid_login: Symbol("EID_LOGIN"),
    private_eid_login_completed: Symbol("PRIVATE_EID_LOGIN_COMPLETED"),
    welcome_eid_login_completed: Symbol("EID_LOGIN_COMPLETED"),
});